Repository vlad-iancu/proiect-ip, pull requests merged in 2021-11, with the labels that each got.

#6 Add template for pull requests
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#8 Feature / Add Config class that holds app properties [#7]
  .gitignore
  conf.sample.json
  src/__init__.py
  src/config/AppEnvironmentEnum.py
  src/config/Config.py
  src/config/DbConfig.py
  src/main.py
  test/__init__.py
  test/conf.test.json
  test/config_tests.py
Labels: enhancement

#11 Fix / Add squash and rebase rule to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#19 Feature / Refactor modules and add CI pipeline [#9]
  .env.example
  .github/workflows/lint-and-test.yml
  .gitignore
  .pep8
  conf.sample.json
  requirements.txt
  run.ps1
  run.sh
  src/__init__.py
  src/config/AppEnvironmentEnum.py
  src/config/Config.py
  src/config/DbConfig.py
  src/config/_Configuration.py
  src/config/_DbConfiguration.py
  src/config/__init__.py
  src/main.py
  test/.env.test
  test/ConfigTests.py
  test/__init__.py
  test/conf.test.json
  test/config_tests.py
Labels: documentation, enhancement

#24 Feature / Add CI pipeline steps for publishing test coverage [#23]
  .github/workflows/python-ci.yml
  requirements.txt
Labels: enhancement

#21 Fix/ps script fix and add schema
  run.ps1
  schema.sql
Labels: bug, documentation, enhancement

#22 Feature/Insert mock data [#20]
  data.sql
  schema.sql
Labels: documentation, enhancement
