Repository vlad-iancu/proiect-ip, pull requests merged in 2022-02, with the labels that each got.

#49 Feature / Add CoffeePreparation tests
  data.sql
  schema.sql
  src/controllers/CoffeePreparationController.py
  src/controllers/CoffeeRecipeController.py
  src/controllers/EnvironmentController.py
  src/controllers/IngredientController.py
  src/models/CoffeePreparation.py
  src/repositories/CoffeePreparationRepository.py
  src/repositories/CoffeeRecipeRepository.py
  src/repositories/IngredientRepository.py
  src/services/CoffeePreparationService.py
  src/services/CoffeeRecipeService.py
  test/CoffeePreparationTests.py
  test/CoffeeRecipeTests.py
  test/__init__.py
Labels: enhancement

#43 Ingredients fix
  clear.sql
  data.sql
  schema.sql
  src/controllers/IngredientController.py
  test/CoffeePreparationTests.py
  test/CoffeeRecipeTests.py
  test/IngredientTests.py
Labels: enhancement

#52 Fix / Add auth secret key and fix user repo
  .env.example
  .env.test
  src/config/Configuration.py
  src/main.py
  src/repositories/UserRepository.py
  src/services/UserService.py
Labels: bug

#55 Feature / Add swagger.yaml schema file and update README [#45]
  README.md
  swagger.yaml
Labels: documentation, enhancement

#51 [WIP] Add Controllers tests
  src/controllers/AuthController.py
  src/controllers/CoffeePreparationController.py
  src/controllers/CoffeeRecipeController.py
  src/controllers/EnvironmentController.py
  src/controllers/IngredientController.py
  src/main.py
  src/models/CoffeeRecipe.py
  src/repositories/CoffeePreparationRepository.py
  src/services/UserService.py
  test/AuthControllerTests.py
  test/CoffeePreparationControllerTests.py
  test/CoffeeRecipeControllerTests.py
  test/EnvironmentControllerTests.py
  test/IngredientControllerTests.py
  test/MainTests.py
  test/__init__.py
Labels: enhancement

#54 Fix / Avoid parsing None when APP_DB_PORT env var is missing
  Dockerfile
  docker-entrypoint.sh
  src/config/Configuration.py
  test/ConfigTests.py
Labels: bug
